#!/bin/bash

set -e -x

GO_VER=${GO_VER:-1.5.2}

mkdir -p  go

export GOPATH="$PWD/go"

git clone https://github.com/asdfsx/telegraf-1.git "$PWD"/go/src/github.com/influxdata/telegraf
docker run -it --rm -v "${GOPATH}":/go -e "GOPATH=/go" -w /go/src/github.com/influxdata/telegraf/ golang:$GO_VER sh -c 'make' 
docker build -t asdfsx/telegraf .
